spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#springboot整合mybatis
mybatis:
  #配置xml的路径
  mapper-locations: classpath:mapper/*.xml
  #配置别名包
  type-aliases-package: com.ujiuye.springbootmybatis01.pojo

